name = "sudoku-mp"
main = "cloudflare/src/index.ts"
compatibility_date = "2026-05-11"
workers_dev = true
preview_urls = false

[assets]
directory = "./client/dist"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "LOBBY"
class_name = "LobbyDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["LobbyDO"]
